"use client"
import { FormEvent, useEffect, useState } from "react"
import { useParams, useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { getExamQuestions, submitExam, type ExamQuestion } from "@/lib/exam-api"
import toast from "react-hot-toast"
export default function ExamPage() { const { id } = useParams<{ id: string }>(); const router = useRouter(); const [questions, setQuestions] = useState<ExamQuestion[]>([]); const [answers, setAnswers] = useState<Record<string,string>>({}); useEffect(() => { getExamQuestions(id).then(setQuestions).catch((e) => toast.error(e?.message || "Unable to load questions")) }, [id]); async function submit(event: FormEvent) { event.preventDefault(); try { await submitExam(id, answers); toast.success("Exam submitted"); router.push(`/results?exam=${id}`) } catch (e: any) { toast.error(e?.message || "Unable to submit exam") } } return <main className="container max-w-3xl py-10"><h1 className="text-3xl font-bold">Exam</h1><form onSubmit={submit} className="mt-6 space-y-5">{questions.map((question, index) => <Card key={question.id}><CardContent className="p-5"><h2 className="font-semibold">{index + 1}. {question.title}</h2><p className="mt-1 text-sm text-muted-foreground">{question.description}</p><div className="mt-4 space-y-2">{question.type === "MCQ" ? question.options?.map((option) => <label key={option.id} className="flex gap-2 rounded border p-3"><input type="radio" name={question.id} required onChange={() => setAnswers((current) => ({ ...current, [question.id]: option.id }))} />{option.option}</label>) : question.type === "TRUE_FALSE" ? ["true", "false"].map((value) => <label key={value} className="flex gap-2 rounded border p-3 capitalize"><input type="radio" name={question.id} required onChange={() => setAnswers((current) => ({ ...current, [question.id]: value }))} />{value}</label>) : <Input required value={answers[question.id] || ""} onChange={(e) => setAnswers((current) => ({ ...current, [question.id]: e.target.value }))} />}</div></CardContent></Card>)}<Button size="lg" disabled={!questions.length}>Submit exam</Button></form></main> }
